// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Use direct connection for schema push/migrate (Supabase port 5432).
  // The app runtime uses DATABASE_URL via the pg adapter in src/lib/db/prisma.ts.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
