import type { DetectorCategory, DetectorDefinition } from "@/lib/scanner/detectors/types";

const GCP_SERVICE_ACCOUNT = /"type"\s*:\s*"service_account"/g;
const AIZA_KEY = /\bAIzaSy[A-Za-z0-9_-]{33}\b/g;

export const DETECTOR_CATALOG: DetectorDefinition[] = [
  // --- AI / ML ---
  {
    id: "anthropic_api_key",
    secretType: "Anthropic API Key",
    category: "ai_ml",
    severity: "Critical",
    baseConfidence: 0.97,
    pattern: /\bsk-ant-api0[3-9]-[A-Za-z0-9_-]{80,}\b/g,
    method: "regex",
    description: "Anthropic Claude API key (sk-ant-api03-...)",
    referenceUrl: "https://docs.anthropic.com/en/api/getting-started",
    contextKeywords: ["anthropic", "claude"],
    validate: (v) => v.startsWith("sk-ant-"),
    priority: 100,
  },
  {
    id: "openai_api_key",
    secretType: "OpenAI API Key",
    category: "ai_ml",
    severity: "Critical",
    baseConfidence: 0.96,
    pattern: /\bsk-(?!ant-)[A-Za-z0-9][A-Za-z0-9_-]{19,}\b/g,
    method: "regex",
    description: "OpenAI API key (sk-...)",
    referenceUrl: "https://platform.openai.com/docs/api-reference",
    contextKeywords: ["openai", "gpt"],
    priority: 95,
  },
  {
    id: "google_gemini_api_key",
    secretType: "Google Gemini API Key",
    category: "ai_ml",
    severity: "Critical",
    baseConfidence: 0.88,
    pattern: AIZA_KEY,
    method: "regex",
    description: "Google API key used by Gemini / Google AI Studio",
    referenceUrl: "https://ai.google.dev/gemini-api/docs/api-key",
    contextKeywords: ["gemini", "google_ai", "generativelanguage", "google cloud"],
    validate: (v) => /^AIzaSy/.test(v),
    priority: 70,
  },
  {
    id: "huggingface_token",
    secretType: "Hugging Face Token",
    category: "ai_ml",
    severity: "High",
    baseConfidence: 0.94,
    pattern: /\bhf_[A-Za-z0-9]{34,}\b/g,
    method: "regex",
    description: "Hugging Face access token (hf_...)",
    referenceUrl: "https://huggingface.co/docs/hub/security-tokens",
    contextKeywords: ["huggingface", "hf_token"],
    priority: 90,
  },

  // --- Cloud providers ---
  {
    id: "gcp_service_account",
    secretType: "Google Cloud Service Account Key",
    category: "cloud_provider",
    severity: "Critical",
    baseConfidence: 0.93,
    pattern: GCP_SERVICE_ACCOUNT,
    method: "context",
    description: "GCP/Firebase service account JSON credential",
    referenceUrl: "https://cloud.google.com/iam/docs/service-account-creds",
    contextKeywords: ["private_key", "client_email", "project_id", "googleusercontent"],
    priority: 85,
  },
  {
    id: "firebase_web_api_key",
    secretType: "Firebase Web API Key",
    category: "cloud_provider",
    severity: "High",
    baseConfidence: 0.9,
    pattern: AIZA_KEY,
    method: "regex",
    description: "Firebase web API key (AIzaSy...)",
    referenceUrl: "https://firebase.google.com/docs/projects/api-keys",
    contextKeywords: ["firebase", "firebaseconfig", "firebaseapp"],
    contextRequired: true,
    validate: (v) => /^AIzaSy/.test(v),
    priority: 75,
  },
  {
    id: "aws_access_key_id",
    secretType: "AWS Access Key ID",
    category: "cloud_provider",
    severity: "Critical",
    baseConfidence: 0.92,
    pattern: /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/g,
    method: "regex",
    description: "AWS access key identifier",
    referenceUrl: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html",
    contextKeywords: ["aws", "amazonaws"],
    priority: 88,
  },
  {
    id: "azure_storage_account_key",
    secretType: "Azure Storage Account Key",
    category: "cloud_provider",
    severity: "Critical",
    baseConfidence: 0.91,
    pattern:
      /\b(?:DefaultEndpointsProtocol|AccountName|AccountKey)=[^;\s]+|AccountKey=[A-Za-z0-9+/]{86}==\b/gi,
    method: "regex",
    description: "Azure Storage connection string or account key",
    referenceUrl: "https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage",
    contextKeywords: ["azure", "blob.core.windows.net", "accountkey"],
    priority: 82,
  },
  {
    id: "azure_client_secret",
    secretType: "Azure Client Secret",
    category: "cloud_provider",
    severity: "Critical",
    baseConfidence: 0.86,
    pattern:
      /\b(?:client_secret|azure_client_secret|AZURE_CLIENT_SECRET)\s*[:=]\s*["']?([a-zA-Z0-9~._-]{34,40})["']?/gi,
    method: "context",
    description: "Azure AD application client secret",
    referenceUrl: "https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app",
    contextKeywords: ["azure", "client_secret", "tenant_id", "client_id"],
    priority: 80,
  },
  {
    id: "cloudflare_api_token",
    secretType: "Cloudflare API Token",
    category: "cloud_provider",
    severity: "High",
    baseConfidence: 0.9,
    pattern:
      /\b(?:CLOUDFLARE_API_TOKEN|CF_API_TOKEN|cloudflare[_-]?api[_-]?token)\s*[=:]\s*["']?([a-zA-Z0-9_-]{40})\b/gi,
    method: "context",
    description: "Cloudflare API token assigned in config (40-char opaque value)",
    referenceUrl: "https://developers.cloudflare.com/fundamentals/api/get-started/create-token/",
    contextKeywords: ["cloudflare", "cf_api"],
    validate: (v) => v.length === 40 && /^[a-zA-Z0-9_-]+$/.test(v),
    priority: 50,
  },
  {
    id: "digitalocean_token",
    secretType: "DigitalOcean Token",
    category: "cloud_provider",
    severity: "High",
    baseConfidence: 0.95,
    pattern: /\b(?:dop|doo)_v1_[a-f0-9]{64}\b/g,
    method: "regex",
    description: "DigitalOcean personal access token",
    referenceUrl: "https://docs.digitalocean.com/reference/api/create-personal-access-token/",
    priority: 92,
  },
  {
    id: "supabase_service_role_key",
    secretType: "Supabase Service Role Key",
    category: "cloud_provider",
    severity: "Critical",
    baseConfidence: 0.94,
    pattern: /\bsb_secret_[A-Za-z0-9_-]{20,}\b/g,
    method: "regex",
    description: "Supabase service role secret key",
    referenceUrl: "https://supabase.com/docs/guides/api/api-keys",
    contextKeywords: ["supabase", "service_role"],
    priority: 91,
  },

  // --- CI/CD & VCS ---
  {
    id: "github_pat_classic",
    secretType: "GitHub Personal Access Token",
    category: "cicd_vcs",
    severity: "Critical",
    baseConfidence: 0.96,
    pattern: /\bghp_[A-Za-z0-9]{36,}\b/g,
    method: "regex",
    description: "GitHub classic personal access token",
    referenceUrl: "https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token",
    priority: 94,
  },
  {
    id: "github_pat_fine_grained",
    secretType: "GitHub Fine-Grained PAT",
    category: "cicd_vcs",
    severity: "Critical",
    baseConfidence: 0.96,
    pattern: /\bgithub_pat_[A-Za-z0-9_]{60,}\b/g,
    method: "regex",
    description: "GitHub fine-grained personal access token",
    priority: 94,
  },
  {
    id: "gitlab_token",
    secretType: "GitLab Token",
    category: "cicd_vcs",
    severity: "Critical",
    baseConfidence: 0.95,
    pattern: /\bglpat-[A-Za-z0-9_-]{20,}\b/g,
    method: "regex",
    description: "GitLab personal access token",
    referenceUrl: "https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html",
    priority: 93,
  },

  // --- Communication ---
  {
    id: "slack_token",
    secretType: "Slack Token",
    category: "communication",
    severity: "High",
    baseConfidence: 0.93,
    pattern: /\bxox[baprs]-[0-9]{10,13}-[0-9]{10,13}-[A-Za-z0-9]{24,}\b/g,
    method: "regex",
    description: "Slack bot or user token",
    referenceUrl: "https://api.slack.com/authentication/token-types",
    priority: 90,
  },
  {
    id: "discord_bot_token",
    secretType: "Discord Bot Token",
    category: "communication",
    severity: "High",
    baseConfidence: 0.9,
    pattern: /\b[MN][A-Za-z\d]{23,}\.[\w-]{6}\.[\w-]{25,}\b/g,
    method: "regex",
    description: "Discord bot token",
    priority: 88,
  },
  {
    id: "telegram_bot_token",
    secretType: "Telegram Bot Token",
    category: "communication",
    severity: "High",
    baseConfidence: 0.9,
    pattern: /\b\d{8,10}:[A-Za-z0-9_-]{35}\b/g,
    method: "regex",
    description: "Telegram bot API token",
    priority: 87,
  },
  {
    id: "sendgrid_api_key",
    secretType: "SendGrid API Key",
    category: "communication",
    severity: "High",
    baseConfidence: 0.96,
    pattern: /\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b/g,
    method: "regex",
    description: "SendGrid API key",
    referenceUrl: "https://docs.sendgrid.com/ui/account-and-settings/api-keys",
    priority: 93,
  },
  {
    id: "twilio_api_key",
    secretType: "Twilio API Key",
    category: "communication",
    severity: "High",
    baseConfidence: 0.94,
    pattern: /\bSK[a-f0-9]{32}\b/g,
    method: "regex",
    description: "Twilio API key (SK...)",
    referenceUrl: "https://www.twilio.com/docs/iam/api-keys",
    contextKeywords: ["twilio"],
    priority: 89,
  },
  {
    id: "twilio_account_sid",
    secretType: "Twilio Account SID",
    category: "communication",
    severity: "Medium",
    baseConfidence: 0.75,
    pattern: /\bAC[a-f0-9]{32}\b/g,
    method: "regex",
    description: "Twilio account SID (often paired with auth token)",
    contextKeywords: ["twilio", "auth_token"],
    contextRequired: true,
    priority: 60,
  },
  {
    id: "resend_api_key",
    secretType: "Resend API Key",
    category: "communication",
    severity: "High",
    baseConfidence: 0.95,
    pattern: /\bre_[A-Za-z0-9]{32,}\b/g,
    method: "regex",
    description: "Resend API key (re_...)",
    referenceUrl: "https://resend.com/docs/api-reference/introduction",
    priority: 91,
  },

  // --- Payment ---
  {
    id: "stripe_live_secret",
    secretType: "Stripe Live Secret Key",
    category: "payment",
    severity: "Critical",
    baseConfidence: 0.96,
    pattern: /\bsk_live_[A-Za-z0-9]{20,}\b/g,
    method: "regex",
    description: "Stripe live secret API key",
    referenceUrl: "https://stripe.com/docs/keys",
    priority: 94,
  },
  {
    id: "stripe_live_publishable",
    secretType: "Stripe Live Publishable Key",
    category: "payment",
    severity: "High",
    baseConfidence: 0.88,
    pattern: /\bpk_live_[A-Za-z0-9]{20,}\b/g,
    method: "regex",
    description: "Stripe live publishable key",
    priority: 85,
  },

  // --- Commerce ---
  {
    id: "shopify_token",
    secretType: "Shopify Token",
    category: "commerce",
    severity: "Critical",
    baseConfidence: 0.95,
    pattern: /\bshp(?:at|ca|ss)_[a-fA-F0-9]{32,}\b/g,
    method: "regex",
    description: "Shopify admin or storefront access token",
    referenceUrl: "https://shopify.dev/docs/apps/auth/admin-app-access-tokens",
    contextKeywords: ["shopify", "myshopify"],
    priority: 92,
  },

  // --- Database ---
  {
    id: "mongodb_connection",
    secretType: "MongoDB Connection String",
    category: "database",
    severity: "Critical",
    baseConfidence: 0.93,
    pattern: /\bmongodb(?:\+srv)?:\/\/[^\s"'`<>]+/gi,
    method: "regex",
    description: "MongoDB connection URI with credentials",
    priority: 86,
  },
  {
    id: "postgres_connection",
    secretType: "PostgreSQL Connection String",
    category: "database",
    severity: "Critical",
    baseConfidence: 0.93,
    pattern: /\bpostgres(?:ql)?:\/\/[^\s"'`<>]+/gi,
    method: "regex",
    description: "PostgreSQL connection URI with credentials",
    priority: 86,
  },
  {
    id: "mysql_connection",
    secretType: "MySQL Connection String",
    category: "database",
    severity: "Critical",
    baseConfidence: 0.91,
    pattern: /\bmysql:\/\/[^\s"'`<>]+/gi,
    method: "regex",
    description: "MySQL connection URI with credentials",
    priority: 86,
  },

  // --- Identity ---
  {
    id: "jwt_token",
    secretType: "JWT Token",
    category: "identity",
    severity: "High",
    baseConfidence: 0.82,
    pattern: /\beyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/g,
    method: "regex",
    description: "JSON Web Token (three base64url segments)",
    referenceUrl: "https://jwt.io/introduction",
    validate: (v) => {
      const parts = v.split(".");
      return parts.length === 3 && parts.every((p) => p.length > 10);
    },
    priority: 65,
  },
  {
    id: "private_key_pem",
    secretType: "Private Key",
    category: "identity",
    severity: "Critical",
    baseConfidence: 0.99,
    pattern: /-----BEGIN (?:RSA |EC |OPENSSH |ENCRYPTED )?PRIVATE KEY-----/g,
    method: "regex",
    description: "PEM-encoded private key material",
    priority: 100,
  },
];

export const SORTED_DETECTOR_CATALOG = [...DETECTOR_CATALOG].sort(
  (a, b) => (b.priority ?? 0) - (a.priority ?? 0),
);

export function getCatalogMeta(): import("@/lib/scanner/detectors/types").DetectorCatalogMeta {
  const categories = [
    ...new Set(DETECTOR_CATALOG.map((d) => d.category)),
  ] as DetectorCategory[];
  return {
    version: "2.0.0",
    totalDetectors: DETECTOR_CATALOG.length,
    categories,
  };
}

export function getDetectorById(id: string): DetectorDefinition | undefined {
  return DETECTOR_CATALOG.find((d) => d.id === id);
}
